use BUILD_DIR argument when copying ssh key
heroku/heroku-buildpack-ssh-key pull request #4
Opened 2021-06-21 21:08 UTC by fivetanley

The new build system (`heroku labs:enable build-in-app-dir`) has a
temporary directory for `$HOME`, so we need to copy things into the
BUILD_DIR argument, which will become home at runtime.

2021-06-21 21:09 UTC, fivetanley commented
cc @edmorley

2021-06-21 21:10 UTC, fivetanley commented
Err whoops, meant to say, @edmorley can you please review?

2021-06-21 21:16 UTC, edmorley requested changes
Hi! Could you explain more about the motivation for this change? As is, it doesn't seem correct. This buildpack is intended for build-time only consumption of the SSH key, which is unchanged even after the `build-in-app-dir` labs is enabled (note: that feature is currently off by default).

After this PR, the SSH key is now also available at runtime, when it was not before.

2021-06-21 21:20 UTC, fivetanley commented
It was needed when enabling the flag. It seems the value of `$HOME` is changing if you have multiple buildpacks. For example, if you use this buildpack first and then the ruby or elixir buildpack with an SSH dependency, the SSH directory set up by this buildpack seems to be missing. Maybe that's a bug with the flag, and not with this buildpack?

2021-06-21 21:24 UTC, edmorley commented
If you write up steps to reproduce, I'd be happy to take a look. However the value of `$HOME` should not change during the build, unless a later buildpack explicitly overrides it via the `export` file. Note however that it's expected that with the labs enabled, `$HOME` at build time vs runtime differs.

2021-06-21 21:27 UTC, edmorley commented
This is all the flag does:
https://github.com/heroku/codon/blob/8ccf44c06cd6275169213515ef2400a6aa69ea22/lib/slug_compiler/slug.rb#L82-L88
https://github.com/heroku/codon/blob/8ccf44c06cd6275169213515ef2400a6aa69ea22/lib/slug_compiler/slug.rb#L98-L104
https://github.com/heroku/codon/blob/8ccf44c06cd6275169213515ef2400a6aa69ea22/lib/slug_compiler/slug.rb#L305

2022-07-12 21:56 UTC, dansobo commented
> If you write up steps to reproduce, I'd be happy to take a look. However the value of `$HOME` should not change during the build, unless a later buildpack explicitly overrides it via the `export` file. Note however that it's expected that with the labs enabled, `$HOME` at build time vs runtime differs.

Hello! FWIW: I have a Rails app where yarn pulls from a private repo via SSH. When `build-in-app-dir` is enabled I'm unable to build the app on Heroku with the current buildpack (see log below). 

I've tested that this PR would indeed resolve the issue, although `.ssh` would also end up in the `/app` directory.

Without this PR:
```
remote:        yarn install v1.22.17
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        error Command failed.
remote:        Exit code: 128
remote:        Command: git
remote:        Arguments: ls-remote --tags --heads ssh://git@github.com/(my private repo).git
remote:        Directory: /app
remote:        Output:
remote:        Host key verification failed.
remote:        fatal: Could not read from remote repository.
remote:        
remote:        Please make sure you have the correct access rights
remote:        and the repository exists.
```

2022-07-13 07:51 UTC, edmorley commented
So I've just tested this buildpack with `build-in-app-dir` enabled and it is working as expected -  as in:
- The `.ssh` directory is available at `$HOME/.ssh` for later buildpacks too.
- `$HOME` doesn't change between buildpacks.

See:

```
$ mkdir testcase-ssh-key && cd $_
$ git init
$ h create
$ h labs:enable build-in-app-dir
$ h config:set BUILDPACK_SSH_KEY=test
$ h buildpacks:add https://github.com/heroku/heroku-buildpack-ssh-key
$ h buildpacks:add heroku-community/inline
$ touch README.md
$ mkdir bin/
$ touch bin/detect
$ echo 'ls -alR $HOME' > bin/compile
$ chmod +x bin/*
$ git add -A; git commit -m '.'; git push heroku main
...
remote: -----> Building on the Heroku-20 stack
remote: -----> Using buildpacks:
remote:        1. https://github.com/heroku/heroku-buildpack-ssh-key
remote:        2. heroku-community/inline
remote: -----> Performing build in /app since 'build-in-app-dir' is enabled
remote: -----> heroku-buildpack-ssh-key app detected
remote: -----> Install heroku-buildpack-ssh-key
remote: -----> Installed SSH key from BUILDPACK_SSH_KEY
remote: -----> https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku-community/inline.tgz app detected
remote: /tmp/build_home:
remote: total 12
remote: drwx------ 3 u52318 dyno 4096 Jul 13 07:44 .
remote: drwx------ 5 u52318 dyno 4096 Jul 13 07:44 ..
remote: drwx------ 2 u52318 dyno 4096 Jul 13 07:44 .ssh
remote:
remote: /tmp/build_home/.ssh:
remote: total 20
remote: drwx------ 2 u52318 dyno 4096 Jul 13 07:44 .
remote: drwx------ 3 u52318 dyno 4096 Jul 13 07:44 ..
remote: -rw------- 1 u52318 dyno   85 Jul 13 07:44 config
remote: -rw------- 1 u52318 dyno    5 Jul 13 07:44 id_rsa
remote: -rw------- 1 u52318 dyno  806 Jul 13 07:44 known_hosts
```

It seems perhaps the issue might be that some tools are not honouring `$HOME` and are performing lookup on the home directory via another means? Or alternatively, perhaps the buildpacks in question are not passing `$HOME` through to the subprocess?

2022-07-13 08:12 UTC, edmorley commented
So trying with ssh verbose mode enabled I can see that OpenSSH isn't for some reason honouring `$HOME` in this case. It's not clear whether it never honours the `$HOME` env var (and only say looks at the system user config, which we can't change), or whether there is some other issue.

It also seems there isn't an env var we can set to force ssh to look at a different directory. Whilst there is `GIT_SSH_COMMAND`, this would only help Git's usage of SSH, not via other means.

Perhaps one option would be to just add a symlink from `$BUILD_DIR/.ssh` to `$HOME/.ssh` in this buildpack iff `$HOME != /app` thereby working around this OpenSSH limitation, whilst not changing the security posture (as the PR in its current form would).

2022-07-13 20:54 UTC, dansobo commented
The symlink `ln -s $HOME/.ssh $BUILD_DIR/.ssh` indeed works, and doesn't leave any keys sitting around or accessible from `/app`. Thanks!

2022-12-07 18:50 UTC, fivetanley commented
closing this PR as I no longer work at Heroku (<3) but no longer wish to receive notifications for this PR. If someone else wants to take up the mantle on this please go ahead.

2022-12-07 18:50 UTC, closed without merging